### ISSUE TITLE
-tv option in bp

### ISSUE THREAD

**Issue by vatanparast** [FePhyFoFum/gophy#6]
Hello,
In the [https://fephyfofum.github.io/gophy/](url) you mentioned to use `-tv` option, but when I add it, `bp` gives not defined error.  `flag provided but not defined: -tv`

Would you please fix it, or other workaround to get list of trees with the conflict, concordance, and uninformative?

I should mention that the option works on mac, but not in the linux cluster. I am not sure why? I have 2 cores in macbook, so prefer to run on cluster.

Thanks
Mohammad

**Comment by blackrim** [comment]
That is really strange. Can you give the inputs? I can't seem to replicate this

**Comment by vatanparast** [comment]
Unfortunately, I do not have the issue log. I recompiled it recently with the latest repo and it worked. May be caused by an old version of go!
